name: Actions Workflow

on:
  pull_request:
      types:
        - reopened
        - opened
        - closed
        - assigned 

jobs:
  run-github-actions:
      runs-on: ubuntu-latest
      steps:
        - name: Echo Variables
          run: |
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
        - name: List Files
          run: |
            pwd
            ls -a
        - name: Checkout Action
          uses: actions/checkout@v3.3.0
        - name: List Files After Checkout
          run: |
            pwd
            ls -a
        - name: Simple Javascript Actions
          id: greet
          uses: actions/hello-world-javascript-action@v1.1
          with:
            who-to-greet: Dragos
        - name: Log Greeting Time
          run: echo "${{ steps.greet.outputs.time }}"