name: Container Workflow

on:
  - push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:14.21-alpine3.16
    steps:
      - name: Log Node version
        run: |
          node -v
          cat /etc/os-release