name: Matrix Workflow

on:
  - push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 6
      - name: Log node version
        run: node -v

