name: Matrix Workflow

on:
  - push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
        include:
          - os: ubuntu-latest
          - node-version: 4
        exclude:
          - os: ubuntu-latest
            node-version: 6
          - os: macos-latest
            node-version: 10
      max-parallel: 2
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log node version
        run: node -v

