name: Assembly Assignment

on:
    - push

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
          - name: Assemble .ASM file
            run: echo "Hello World"
          - name: Multiline script
            run: |
              node -v
              npm -v
          - name: Python Test
            run: |
              import platform
              print(platform.processor())
            shell: python
