name: Automated Homework Testing - Assembly Language

on:
  - push

jobs:
  build-run-test:
    runs-on: ubuntu-latest
    env:
      USER_ENTRY_EXISTS: false
    steps:
      - name: Checkout source .asm files
        uses: actions/checkout@v3.3.0
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Environment Setup
        run: |
          sudo apt-get install -y dosbox
      - name: Decrypt File
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/arhitecturi-bot.json arhitecturi-bot.json.gpg
      # - name: Save result in spreadsheet
      #   run: |
          
      # - name: Execute binary and save output
      #   env:
      #     TERM: xterm
      #   run: |
      #     sudo dosbox -c "mount c ." -c "c:" -c "homework.com >> output.txt" -c "exit"
      # - name: Setup Google Sheets Cell Data
      #   run: |
      #     echo "CELL_DATA_NAME=$(cat OUTPUT.TXT | head -n 1 | cut -f1 -d:)" >> $GITHUB_ENV
      #     echo "CELL_DATA_CLASS=$(cat OUTPUT.TXT | head -n 1 | cut -f2 -d:)" >> $GITHUB_ENV
      #     echo "CELL_DATA_RESULT=0" >> $GITHUB_ENV