name: Automated Homework Testing - Assembly Language

on:
  - push

jobs:
  build-run-test:
    runs-on: ubuntu-latest
    env:
      USER_ENTRY_EXISTS: false
    steps:
      - name: Checkout source .asm files
        uses: actions/checkout@v3.3.0
      - name: List Files After Checkout
        run: |
          pwd
          ls -a 
      - name: Environment Setup
        run: |
          sudo apt-get install -y dosbox
      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install googleapis
      - name: Decrypt File
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $GITHUB_WORKSPACE/homework/arhitecturi-bot.json $GITHUB_WORKSPACE/homework/arhitecturi-bot.json.gpg 
      - name: Execute binary and save output
        env:
          TERM: xterm
        run: |
          cd $GITHUB_WORKSPACE/homework
          ./runHomework.sh
      - name: Set updated spreadsheet properties in environment variables
        run: |
          echo "SHEET_ID=$(tail -n 2 $GITHUB_WORKSPACE/homework/out/README | head -n 1 | cut -f2 -d=)" >> $GITHUB_ENV
          echo "CELL_NUMBER=$(tail -n 1 $GITHUB_WORKSPACE/homework/out/README | cut -f2 -d=)" >> $GITHUB_ENV
          echo "RESULT=$(tail -n 1 $GITHUB_WORKSPACE/homework/out/OUTPUT)" >> $GITHUB_ENV  
      - name: Update spreadsheet 
        run: |
          node $GITHUB_WORKSPACE/homework/update-spreadsheet.js $SPREADSHEET_ID $SHEET_ID $CELL_NUMBER $RESULT
        env:
          SPREADSHEET_ID: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          SHEET_ID: ${{ env.SHEET_ID }}
          CELL_NUMBER: ${{ env.CELL_NUMBER }}
          RESULT: ${{ env.RESULT }} 